### ISSUE TITLE
Tamil Bible Support

### ISSUE THREAD

**Issue by mangoose20026** [aicwebtech/biblesupersearch_api#26]
Can you please add support for tamil bible like English. Tamil bible is available in all formats whichever you like to use (https://github.com/godlytalias/Bible-Database/tree/master/Tamil)

**Comment by aicwebtech** [comment]
We will be adding several Bibles in the upcoming 5.6 release and Tamil language will be included.

**Comment by mangoose20026** [comment]
Thank you so much !

**Comment by aicwebtech** [comment]
Tamil Bible support was added as part of today's release.  Closing this out.
